language: python

arch:
  - arm32

python:
  - "3.7"

services:
  - docker

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: test
      skip_cleanup: true
      script: pipenv run; pytest

notifications:
  email: false
