language: python

arch:
  - arm32

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

jobs:
  include:
    - stage: test
      script: pytest --cov=xdrone --cov-fail-under=100

notifications:
  email: false
